In [2]:
import numpy as np

In [3]:
print(np.array([1,2,3,4]))          #Created a np array, np array is a homogenous array, also known as n-dimensional

[1 2 3 4]


In [8]:
print(np.zeros([3,3]))               #Created a 3x3 matrix with each element=0

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
ones_m=np.ones([3,3])               #Created a 3x3 matrix with each element=1
print(ones_m)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
my_array=np.array([1,3,5,2,4,6])
print(np.reshape(my_array,(2,3)))      #Reshape= giving new size

[[1 3 5]
 [2 4 6]]


In [29]:
array1=np.array(['element_1','element_2'])
array2=np.array(['element_3','element_4'])
print(np.concatenate((array_1,array_2),axis=0))       #Concatinating along vertical axis

[['element_1']
 ['element_2']
 ['element_3']
 ['element_4']]


In [19]:
array_3=np.array([[1,2,3],[3,4,5]])
print(np.mean(array_3))                              #mean of all values of array
print(np.mean(array_3,axis=0))                       #mean of values of each column
print(np.mean(array_3,axis=1))                       #mean of values of rows

3.0
[2. 3. 4.]
[2. 4.]


In [20]:
array_4=np.array([[3,4,5],[6,7,8]])
print(np.sum(array_4))                              #sum of all values
print(np.sum(array_4,axis=0))                       #sum of values of each column
print(np.sum(array_4,axis=1))                       #sum of values of each row

33
[ 9 11 13]
[12 21]


In [21]:
array_5=np.array([[1,2,3],[4,5,6]])
print(np.min(array_5))                              #minimum value from whole array
print(np.min(array_5,axis=0))                       #minimum from each column
print(np.min(array_5,axis=1))                       #minimum from each row

1
[1 2 3]
[1 4]


In [22]:
array_6=np.array([[10,11,2],[20,22,33]])
print(np.max(array_6))                             #max value from whole array
print(np.max(array_6,axis=0))                      #max value from each column
print(np.max(array_6,axis=1))                      #max value from each row

33
[20 22 33]
[11 33]


In [23]:
array_7=np.array([[17,14],[45,68]])
print(np.argmax(array_7))                         #index of maximum value of whole array
print(np.argmin(array_7))                         #index of minimum value of whole arra

3
1


In [27]:
print(np.random.rand(2,3))                          #Gives random float numbers between 0 and 1 in an array of size 2x3
print(np.random.randn(3))                           #Gives a random scalar from a standard normal distribution(mean=0,standard deviation=1)
print(np.random.randint(1,11,size=(2,3)))           #Gives random numbers between 1 to 11 excluding 11 (including 1) in an array of order 2x3

[[0.96986487 0.38861247 0.08005845]
 [0.87184382 0.70930767 0.70978466]]
[-2.38978911  0.73127772 -0.47265028]
[[ 8  5  4]
 [10  6  6]]


In [28]:
matrix_1=np.array([[1,2],[2,4]])
matrix_2=np.array([[3,4],[5,6]])
print(np.dot(matrix_1,matrix_2))                    #Gives matrix multiplication, and gives vector products in case of vectors

[[13 16]
 [26 32]]
